"""Oracle Kernel — File-system-based orchestration layer."""

from .manifest import (
    create_manifest,
    load_manifest,
    save_manifest,
    update_agent_status,
    set_human_action,
    clear_human_action,
    list_investigations,
    investigation_dir,
    manifest_path,
)
from .context_store import ContextStore
from .agent_runner import AgentRunner
from .skill_loader import SkillLoader
from .skill_registry import SkillRegistry
from .human_hook import pause_for_human, display_brief_summary
from .llm_client import LLMClient, LLMResponse
from .intelligence import (
    Claim,
    Contradiction,
    AdversarialFinding,
    AntiPatternCheck,
    PreShipValidator,
    PreShipResult,
    apply_tier_marking,
    tag_text_with_tiers,
    detect_contradictions,
    run_adversarial_pass,
    enforce_anti_patterns,
    generate_brief_section,
    should_redistill,
    mark_distilled,
    TIER_CAP_BY_ACCESS,
    TIER_DEFINITIONS,
    ANTI_PATTERNS,
)
from .formatters import (
    format_contradiction_map,
    format_adversarial_findings,
    format_tier_marking,
    generate_uncertainty_map,
    compile_brief,
    generate_synthesis,
    format_anti_patterns,
    extract_thesis,
    summarize_evidence,
    count_tiers,
    format_video_catalog_md,
    format_facts_md,
    build_harvester_json,
)
from .video_pipeline import (
    ProcessedVideo,
    download_video,
    extract_frames,
    extract_audio,
    transcribe_audio,
    process_video_source,
    process_all_sources,
    get_source_evidence,
)

__all__ = [
    "create_manifest",
    "load_manifest",
    "save_manifest",
    "update_agent_status",
    "set_human_action",
    "clear_human_action",
    "list_investigations",
    "investigation_dir",
    "manifest_path",
    "ContextStore",
    "AgentRunner",
    "SkillLoader",
    "SkillRegistry",
    "pause_for_human",
    "display_brief_summary",
    # LLM client
    "LLMClient",
    "LLMResponse",
    # Intelligence layer
    "Claim",
    "Contradiction",
    "AdversarialFinding",
    "AntiPatternCheck",
    "PreShipValidator",
    "PreShipResult",
    "apply_tier_marking",
    "tag_text_with_tiers",
    "detect_contradictions",
    "run_adversarial_pass",
    "enforce_anti_patterns",
    "generate_brief_section",
    "should_redistill",
    "mark_distilled",
    "TIER_CAP_BY_ACCESS",
    "TIER_DEFINITIONS",
    "ANTI_PATTERNS",
    # Formatters
    "format_contradiction_map",
    "format_adversarial_findings",
    "format_tier_marking",
    "generate_uncertainty_map",
    "compile_brief",
    "generate_synthesis",
    "format_anti_patterns",
    "extract_thesis",
    "summarize_evidence",
    "count_tiers",
    # Harvester formatters
    "format_video_catalog_md",
    "format_facts_md",
    "build_harvester_json",
    # Video pipeline
    "ProcessedVideo",
    "download_video",
    "extract_frames",
    "extract_audio",
    "transcribe_audio",
    "process_video_source",
    "process_all_sources",
    "get_source_evidence",
]
